### ISSUE TITLE
How you managed to get the offense ID?

### ISSUE THREAD

**Issue by alan7s** [Mpak1996/QRadar_Jira_Integration#1]
Hey, nice work 

But, how you managed to get the offense ID since you can't get the offense ID  by Network Event Property from Custom Actions edit menu?

**Comment by b4k0** [comment]
Hi @alan7s ,

- It needed to create an Offense rule:
  - [x] Test: when an offense is created 
  - [x] Action: send to local syslog (SIM-Audit-2), it creates a new event. Please, note the QID.
- It needed to parse the value of offense ID as custom variable. It can be done directly inside the above event.
- It needed to create an Event rule:
  - [x] Test:  when the event QID is one of the following "QID of Offense Created"
  - [x] Action: run Custom Actions (script)
4. Finally, you can find offenseID as Network Event Property on Custom Actions

Cheers🚀
